"""initial schema

Revision ID: 9a6857dcba76
Revises:
Create Date: 2026-09-21 20:38:00.419553
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9a6857dcba76"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated from app/models.py, then reviewed.
    op.create_table(
        "alerts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=True),
        sa.Column("detection_stage", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("anomaly_score", sa.Float(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("src_ip", sa.String(length=45), nullable=False),
        sa.Column("src_port", sa.Integer(), nullable=True),
        sa.Column("dst_ip", sa.String(length=45), nullable=False),
        sa.Column("dst_port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=16), nullable=True),
        sa.Column("asset_criticality", sa.String(length=16), nullable=True),
        sa.Column("host_prior_alert_count", sa.Integer(), nullable=False),
        sa.Column("mitre_technique", sa.String(length=64), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("recommended_actions", sa.JSON(), nullable=True),
        sa.Column("raw_flow", sa.JSON(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("ground_truth_label", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'UNCLASSIFIED_ANOMALY' AND family IS NULL) OR (kind = 'KNOWN' AND family IS NOT NULL)",
            name=op.f("ck_alerts_family_matches_kind"),
        ),
        sa.CheckConstraint(
            "detection_stage IN ('stage1_supervised', 'stage2_anomaly')",
            name=op.f("ck_alerts_detection_stage_valid"),
        ),
        sa.CheckConstraint(
            "kind IN ('KNOWN', 'UNCLASSIFIED_ANOMALY')", name=op.f("ck_alerts_kind_valid")
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_alerts_severity_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('replay', 'live', 'api')", name=op.f("ck_alerts_source_valid")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_review', 'closed', 'dismissed')",
            name=op.f("ck_alerts_status_valid"),
        ),
        sa.CheckConstraint(
            "occurrence_count >= 1", name=op.f("ck_alerts_occurrence_count_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alerts_dedupe_key_last_seen", ["dedupe_key", "last_seen"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alerts_detected_at"), ["detected_at"], unique=False)
        batch_op.create_index("ix_alerts_kind_detected_at", ["kind", "detected_at"], unique=False)
        batch_op.create_index(
            "ix_alerts_src_ip_detected_at", ["src_ip", "detected_at"], unique=False
        )
        batch_op.create_index("ix_alerts_status_risk_score", ["status", "risk_score"], unique=False)

    op.create_table(
        "model_versions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("supervised_algorithm", sa.String(length=64), nullable=True),
        sa.Column("anomaly_algorithm", sa.String(length=64), nullable=True),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trained_on", sa.String(length=255), nullable=True),
        sa.Column("schema_hash", sa.String(length=80), nullable=True),
        sa.Column("tau_sup", sa.Float(), nullable=True),
        sa.Column("tau_anom", sa.Float(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('champion', 'challenger', 'archived')",
            name=op.f("ck_model_versions_stage_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_model_versions_version")),
    )
    op.create_table(
        "analyst_verdicts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("alert_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("analyst", sa.String(length=128), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('TP', 'FP', 'UNSURE')", name=op.f("ck_analyst_verdicts_verdict_valid")
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_analyst_verdicts_alert_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyst_verdicts")),
    )
    with op.batch_alter_table("analyst_verdicts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analyst_verdicts_alert_id"), ["alert_id"], unique=False
        )
        batch_op.create_index(
            "ix_analyst_verdicts_created_at_verdict", ["created_at", "verdict"], unique=False
        )


def downgrade() -> None:
    # Autogenerated from app/models.py, then reviewed.
    with op.batch_alter_table("analyst_verdicts", schema=None) as batch_op:
        batch_op.drop_index("ix_analyst_verdicts_created_at_verdict")
        batch_op.drop_index(batch_op.f("ix_analyst_verdicts_alert_id"))

    op.drop_table("analyst_verdicts")
    op.drop_table("model_versions")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_status_risk_score")
        batch_op.drop_index("ix_alerts_src_ip_detected_at")
        batch_op.drop_index("ix_alerts_kind_detected_at")
        batch_op.drop_index(batch_op.f("ix_alerts_detected_at"))
        batch_op.drop_index("ix_alerts_dedupe_key_last_seen")

    op.drop_table("alerts")
